name: Create Release
on: 
  push:
    branches:
    - main


jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Environment Variables
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "GH_VERSION<<$EOF" >> "$GITHUB_ENV"
        make git_version >> "$GITHUB_ENV"
        echo "$EOF" >> "$GITHUB_ENV"
        
    - name: Echo Environment Variables
      run: |
        echo $GH_VERSION

    # - name: Create release (if new version)
    #   if: ${{ env.RESULT }} == 'PASS'
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
    #   run: |
    #     echo curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/kdmiltner/test/releases -d '{"tag_name":"$(strip ${{ env.NEW_VERSION }})","target_commitish":"main","name":"$(strip ${{ env.NEW_VERSION }})","body":"Deployed on ${{ env.DATE }}","draft":false,"prerelease":false,"generate_release_notes":true}'
