name: Create Release
on: 
  push:
    branches:
    - main


jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Get release status
      run: |
        echo "DATE=$(date "+%Y-%m-%dT%H:%M:%SZ%z")" >> $GITHUB_ENV

    # - name: Set New Version
    #   run: 
    #     echo "NEW_VERSION=$(make code_version)" >> $GITHUB_ENV

    # - name: Set Date
    #   run:
    #     echo "DATE=$(make date)" >> $GITHUB_ENV

    # - name: Create release (if new version)
    #   if: ${{ env.RESULT }} == 'PASS'
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
    #   run: |
    #     echo "curl -L -X POST -H "Accept: application/vnd.github+json" \
    #       -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
    #       -H "X-GitHub-Api-Version: 2022-11-28" \``
    #       https://api.github.com/repos/kdmiltner/test/releases \
    #       -d '{"tag_name":"$(strip ${{ env.NEW_VERSION }})","name":"$(strip ${{ env.NEW_VERSION }})","body":"Deployed on ${{ env.DATE }}","draft":false,"prerelease":false,"generate_release_notes":true}')
