name: Deploy
on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Test'
        required: false
        default: 'main'

jobs:
  create-release: 
    uses: kdmiltner/test/.github/workflows/create_release.yaml@main
    with:
      version: ${{ jobs.create-release.outputs.version }}

  echo-version:
    runs-on: ubuntu-latest
    steps:
      - name: Echo version
        run: echo ${{ needs.create-release.outputs.version }}
